apiVersion: v1
kind: Service
metadata:
  name: k8s-producer-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: k8s-producer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001