apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: k8s-consumer-deployment
  labels:
    app: k8s-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-consumer
  template:
    metadata:
      labels:
        app: k8s-consumer
    spec:
      containers:
        - name: k8s-consumer
          image: greenpython/k8s-consumer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080