apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-producer-deployment
  labels:
    app: k8s-producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-producer
  template:
    metadata:
      labels:
        app: k8s-producer
    spec:
      containers:
        - name: k8s-producer
          image: greenpython/k8s-producer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80